### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by arnoldtaw** [BIG-RAT/SYM-Helper#1]
Unable to type in password (for username and password authentication) and also unable to authenticate via API client. Cannot type/paste Client Secret.

**Comment by BIG-RAT** [comment]
v0.7.7 should resolve the issue.

**Comment by dan-snelson** [comment]
Issue appears to be resolved for me with `0.7.7 (20230919-91A)`.

**Comment by dan-snelson** [comment]
@arnoldtaw:

Have you had a chance to test `0.7.7`?

**Comment by arnoldtaw** [comment]
@dan-snelson Yes, and the login was success.
