### ISSUE TITLE
When opening a previously created configuration, keep everything in the same order they were created in. 

### ISSUE THREAD

**Issue by TheFritz01** [BIG-RAT/SYM-Helper#11]
When a configuration is first created, everything is listed in the Policy Array Items in the proper order, including the grouped items.  The generated script has everything in the correct order as well.

However,  when launching SYM-Helper after it has been closed out and it connects to Jamf and grabs the previous configuration, all the Items are there, but they are now in alphabetical order and not in the order it was originally configured with.  The grouped Items still show up under the proper array, but everything else is out of place. This behavior also carries over to the generated script.

It's very possible that this functionality is already in the utility and I am just missing it, but in the event it isn't, keeping all the Policy Array Items and Grouped Items in the same order as the first configuration would be very helpful in maintaining a current build script. 

Thanks for the great work on this amazing utility!

**Comment by dan-snelson** [comment]
@TheFritz01: Will you please test with version `0.8.1` ?

**Comment by TheFritz01** [comment]
@dan-snelson 

I am guessing I should be testing starting from scratch and not with the configuration I had created with the previous version?  If so, then I will do that.  Otherwise I do have that version installed.

**Comment by dan-snelson** [comment]
@TheFritz01:

Yes, please select: **Action > Clear** and re-re-re-try.


--
Dan

**Comment by BIG-RAT** [comment]
0.8.1 resolved this.  For configurations created with previous versions you'll need to re-order them once in version 0.8.1 or above.
