### ISSUE TITLE
Add option to disable/modify asset tag regular expression

### ISSUE THREAD

**Issue by PaperFixie** [BIG-RAT/SYM-Helper#14]
I ran into an issue testing the generated script where the asset tag validation regex failed because our tags follow the format of 10.1234. I was able to resolve this by modifying the script directly after it generated, but it would be nice to have an option to toggle that validation on or off and then also to modify the regex used.

**Comment by dan-snelson** [comment]
Thanks for the suggestion, @PaperFixie. 

While I’ll defer to @BIG-RAT, to me, this is an adjustment best left up to the admin and the preferred code editor.

**Comment by dev-yeet** [comment]
i came here to make the same request, and i agree.  if you're using the helper, the generated script will use the default regex. it's not a problem to modify after, but it would be nice to be able to have more granular control over each setting. not every organization follows the same asset tag conventions.

**Comment by dan-snelson** [comment]
Thanks for the feedback, @dev-yeet; however, I'm still in the "we'll fix it in post" camp on this one.

**Comment by dan-snelson** [comment]
@PaperFixie:

After counseling together, I’m going to close this issue (although we do like the idea of being able to disable to `regex`.)
