### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by ejadadic** [BIG-RAT/SYM-Helper#5]
When opening SYM-Helper I get prompted to authenticate, using the Client ID/secret or the username/password results into a SYM-Helper quitting unexpectedly. 

 
![Screenshot 2023-09-20 at 9 13 49 AM](https://github.com/BIG-RAT/SYM-Helper/assets/56453048/7e2004f4-5137-4946-9dbc-b72dee5c2595)

- Running macOS 13.5.2
 - SYM-Helper version (i.e., 0.7.7 (20230919-91A)

**Comment by ejadadic** [comment]
API Client Group with the following roles
Read Departments, Read Policies, Read Buildings

**Comment by ejadadic** [comment]
> @ejadadic: Please see the **Pro Tip** in [3. Connections](https://snelson.us/2023/09/introducing-sym-helper/#3).
> 
> If you backup / delete `group.PS2F6S478M.jamfie.SharedJPMA.plist`, can you login?

This worked!

**Comment by dan-snelson** [comment]
Added a [FAQ](https://snelson.us/2023/09/introducing-sym-helper/#faq):

> SYM-Helper crashes immediately after entering server credentials
