### ISSUE TITLE
Ability to add the same policy more than once

### ISSUE THREAD

**Issue by TheFritz01** [BIG-RAT/SYM-Helper#7]
We have a couple policies that we add to multiple List Item groups.  Currently, once a policy is added, it can’t be selected again without manually adding it in the generated script.

**Comment by dan-snelson** [comment]
Thanks for the FR, @TheFritz01.

To clarify, you're calling the **same** Jamf Pro policy multiple times in the **same** SYM _Configuration_?

**Comment by TheFritz01** [comment]
@dan-snelson   Correct. I know it sounds odd, but they are simple policies like adding a wait before proceeding to the next object in a list item. We have a couple complicated apps that we cache first and then run some custom configurations via multiple policies. Not ideal, but they are pretty specific to how our environment is setup.

**Comment by dan-snelson** [comment]
Thanks for the additional details, @TheFritz01.

(_Personally_, my gut tells me this is a job for your code editor of choice, but, I'll defer to @BIG-RAT.)

**Comment by BIG-RAT** [comment]
Policies have the same progress text/icon?

**Comment by TheFritz01** [comment]
Yep, nothing different there.

**Comment by BIG-RAT** [comment]
Added to v0.8.0
Select a policy that's been added and hit command+D

**Comment by TheFritz01** [comment]
> Added to v0.8.0
Select a policy that's been added and hit 


Much appreciated!  Thank you.
